### ISSUE TITLE
Have the method argument stubs not be typed or be less specific

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ttt-5-move-rb#17]
Student ran into an issue converting the position to an integer too early and got:

```
1) ./bin/move executing a CLI Application calls move passing the user input
Failure/Error: run_file("./bin/move")
# received :move with unexpected arguments
expected: (anything, "1", *(any args))
got: ([" ", " ", " ", " ", " ", " ", " ", " ", " "], 1, "X")
```

We can change that stub to be less specific...

**Comment by bryantheastronaut** [comment]
Has there been a fix to this issue? I seem to be running into the same problem. Everything is working properly when I run bin/move, but the test is failing because of that reason. I'm not really sure where would be a better place to convert the input to an integer than in the input variable.

**Comment by AnnJohn** [comment]
Hi @bryantheastronaut we haven't gotten to fix it yet, but will soon. For now, please use the Ask a Question tool in Learn and someone from our support team will get back to you right away. Thanks.

**Comment by trevorberman** [comment]
Hi @aviflombaum I just ran into this issue another way that made it difficult to pass the tests. As currently written in instructions, #to_i is mentioned in Part I, but seemingly not baked into tests. So, neglecting to add that into #move (in move.rb) still passes green. Later, when collecting user input (gets.strip in Part II) previously passing tests broke, but NOT explicitly clear in red test explanations this was because previous un-tested/lacking #to_i <-- Made it harder to debug (though I still had fun doing so!) Can this be tested earlier or assignment instructions be clarified?

**Comment by mendelB** [comment]
Fixed with the above referenced merge. The test is now indifferent as to whether the users data is passed to `move` as a String or an Integer
