### ISSUE TITLE
Incorrect tests

### ISSUE THREAD

**Issue by AlexBevan** [learn-co-curriculum/ttt-5-move-rb#41]
https://learn.co/tracks/bootcamp-prep/ruby-fundamentals/command-line-applications/tic-tac-toe-move

The tests are testing for topics not covered, at this point we are only ensuring a user can input a single move, the tests are testing for more than this, testing if the user has won but 3 in a row etc.

**Comment by AlexBevan** [comment]
![image](https://cloud.githubusercontent.com/assets/11537058/26276169/c8eed0e2-3d69-11e7-9230-586bf8eda31c.png)

**Comment by gj** [comment]
Hi there,

Would you mind providing a bit more detail about the issue?

Thanks! 🙂

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue is being closed now as stale. If the issue is encountered again, please first consult the [Learn Help Center](http://help.learn.co/) and the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature. If neither of those options resolves the problem and you still feel that this is an issue with the curriculum, please reopen this issue and provide as much detail as possible:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 🙂
