### ISSUE TITLE
Pass by value

### ISSUE THREAD

**Issue by AnthonyCatalfo** [learn-co-curriculum/ttt-5-move-rb#46]
arr1=[1,2,3]
arr2=arr1
arr2<<4
print arr1 
If Ruby passed by value then arr1=[1,2,3] but 
it doesn't. arr1=[1,2,3,4]
Ruby passes by reference value.

**Comment by drakeltheryuujin** [comment]
Hi @AnthonyCatalfo ,

Would you mind providing a bit more detail about the issue you are raising? Is there a specific part of the lesson that you think should be modified to accommodate this information? Is this information that you think should be discussed more in depth for students?

Thanks! 💙

**Comment by sgharms** [comment]
I think that the issue here is this:

```ruby
r = [1,2,3]
r2 = r

def frazzle(a, i, newval)
  a[i] = newval
  puts a.object_id
end

puts r.object_id
frazzle(r,1,"test")
puts r.object_id

puts "r: #{r} #{r.object_id}"
puts "r2: #{r2} #{r2.object_id}"


#++++

s1 = 220
s2 = s1
s1 = 999

puts "s1: #{s1} - s2 #{s2}"
```

```text
70335382906760
70335382906760
70335382906760
r: [1, "test", 3] 70335382906760
r2: [1, "test", 3] 70335382906760
s1: 999 - s2 220
```

The language here gets bafflingly complex. Ruby isn't truly PBR or PBV. It's probably a mistake to bring those terms in (versus C++ where it's required). 


@drakeltheryuujin  I think the paragraph under the code sample could use some fleshing out and will do.
